# Generated by Django 4.0.2 on 2022-03-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0004_rename_content_articles_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PassWord',
            field=models.CharField(default=22122002, max_length=100),
        ),
    ]
