# Generated by Django 4.0.2 on 2022-03-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0005_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PassWord',
            field=models.CharField(max_length=100),
        ),
    ]
