# Generated by Django 4.0.2 on 2022-03-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0006_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=225)),
                ('GroupCode', models.IntegerField()),
            ],
        ),
    ]
