# Generated by Django 4.0.2 on 2022-03-08 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0008_user_groupuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='GroupUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidemo.groupuser'),
        ),
    ]
