# Generated by Django 4.0.2 on 2022-03-17 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0009_alter_user_groupuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=225)),
                ('GroupCode', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='groupuser',
            name='GroupCode',
        ),
        migrations.RemoveField(
            model_name='groupuser',
            name='GroupName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='GroupUser',
        ),
        migrations.AddField(
            model_name='groupuser',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apidemo.user'),
        ),
        migrations.AddField(
            model_name='groupuser',
            name='Group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apidemo.group'),
        ),
    ]
