# Generated by Django 4.0.2 on 2022-03-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0011_remove_group_groupcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='PassWord',
            new_name='Password',
        ),
    ]
