# Generated by Django 4.0.2 on 2022-03-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0012_rename_password_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Content',
            field=models.CharField(max_length=200000),
        ),
    ]
