# Generated by Django 4.0.2 on 2022-04-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0013_alter_articles_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.IntegerField(null=True),
        ),
    ]
